### ISSUE TITLE
Perhaps select a SPDX valid license?

### ISSUE THREAD

**Issue by balupton** [piranha/cyrax#4]
Hi, as poetic as the poetic license is, a lot of enterprise customers will not accept it as it does not seem OSI approved. Perhaps selecting one from https://spdx.org/licenses/ would be best? Perhaps the Unlicense would be best?

How I came across this? I am rejigging staticsitegenerators.net to use SPDX license identifiers such that visitors to the website can know exactly what license projects use. SPDX allows this, as because it is standardised there is a lot of tooling for it, such as: https://www.npmjs.com/package/spdx

**Comment by piranha** [comment]
Ha-ha, totally forgot about it. :-)) Switched to ISC license.
