### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by cxong** [piranha/cyrax#6]
Cyrax doesn't work with python 3. When installing it using pip, the following error is returned:

```
$ pip install -r requirements.txt
Collecting cyrax==2.7 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/73/7a/27cb66190a5bd19c41429b77a28ac837d2b1108c692970246d6f9cc931e1/cyrax-2.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1se4ujwz/cyrax/setup.py", line 9, in <module>
        import cyrax
      File "/tmp/pip-build-1se4ujwz/cyrax/cyrax/__init__.py", line 37
        print 'Cyrax', __version__
                    ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print 'Cyrax', __version__)?
```

**Comment by piranha** [comment]
It does not, that's true. :-) It could be done, though. :)

**Comment by cxong** [comment]
Hmm looks like one of the forks has already made python3 changes. These commits:
https://github.com/memiks/cyrax/commit/b5bc798bbec17f82f451d55318c84e133b7ebcdb
https://github.com/memiks/cyrax/commit/897fb59f256fdf217d90ac64d9d583aa7e927ddc

Wonder why they haven't submitted a PR? We could just cherry pick these.

**Comment by piranha** [comment]
Hmmm... I'm still a little bit uneasy about dropping Python2 support. %)

**Comment by cxong** [comment]
no, we should be able to support both 2 and 3. With Travis CI it should be easy to check.
